language: bash

services:
  - docker

before_install:
- docker pull wealizedigital/alastria-node-t-checker:latest

script:
- docker run wealizedigital/alastria-node-t-checker /bin/sh -c "cd validator && poetry run python -m main.py"
